name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Pull Comrak
        run: curl -sS https://webi.sh/comrak | sh

      - name: Run build script
        run: ./build.sh
        shell: bash

      - name: create CNAME
        run: echo $env:DOMAIN_NAME > output/CNAME
        shell: bash

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
      
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output